version: "3.8"
services:
  wp-db:
    image: mysql:latest
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_local 
      MYSQL_USER: wp_user 
      MYSQL_PASSWORD: password 
  wp:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - wp-db
    ports:
      - 10000:80
    environment:
      WORDPRESS_DB_HOST: wp-db:3306 
      WORDPRESS_DB_USER: wp_user 
      WORDPRESS_DB_PASSWORD: password 
      WORDPRESS_DB_NAME: db_local 
      WORDPRESS_DEBUG: 1 
    volumes:
      - ./html:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_ingrid
    restart: always
    depends_on:
      - wp-db
    ports:
      - 10009:80